language: node_js
git:
  depth: 10
node_js:
  - "0.12"
addons:
  apt:
    packages:
      - ruby
before_install:
  - npm install -g grunt-cli
  - gem install --no-ri compass
  - gem install --no-ri scss-lint
install:
  - npm install

